### ISSUE TITLE
[Bug]: Error while parsing OAuth2 state: invalid length

### ISSUE THREAD

**Issue by andriktr** [oauth2-proxy/oauth2-proxy#2833]
### OAuth2-Proxy Version

7.7.1

### Provider

azure

### Expected Behaviour

- No error in logs
- No  500 Error page
-  My app page opens right after auth. 

### Current Behaviour

When I login the following error is shown: 
![image](https://github.com/user-attachments/assets/b9cbbf87-e08f-40a9-986e-eeb05c733f42)

At the same time in the logs I see that authentication was successful,but ` [oauthproxy.go:875] Error while parsing OAuth2 state: invalid length` is thrown.

If I press go back on error page my app page successfully opens. 

Important note here that if I disable `- --whitelist-domain=".myapp.domain.com` argument everything looks good and  the app page opens as expected right after auth, but then in this case I see these errors in the log: 
```
 [2024/10/31 10:35:04] [validator.go:60] Rejecting invalid redirect "https://myapp.domain.com/oauth2/callback": domain / port not in whitelist
[2024/10/31 10:35:04] [validator.go:63] Rejecting invalid redirect "/oauth2/start?rd=https://myapp.domain.com/oauth2/callback": not an absolute or relative URL
 [2024/10/31 10:35:04] [director.go:85] Invalid redirect provided in rd querystring parameter: https://myapp.domain.com/oauth2/callback
 [2024/10/31 10:35:04] [director.go:85] Invalid redirect generated from X-Forwarded-Uri header: /oauth2/start?rd=https://myapp.domain.com/oauth2/callback
```

Same config with version 7.7.0 also drops an error in logs  but bit different one. 

```
runtime error: index out of range [0] with length 0
goroutine 81 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0xe00a80, 0xc0000de330})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/cookies.ExtractStateSubstring(0xc00025f301?)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/cookies/csrf.go:222 +0x91
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/cookies.GenerateCookieName(0x203000?, 0xc00024e520)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/cookies/csrf.go:94 +0x2c
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/cookies.LoadCSRFCookie(0xc0003aeb00, 0x0?)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/cookies/csrf.go:77 +0x27
```
Also instead of 500 page  I receive 403. 
In 7.7.0 disabling --whitelist-domain follows the success auth and redirect to the app page but has same errors like it is in 7.7.1

```
 [2024/10/31 10:35:04] [validator.go:60] Rejecting invalid redirect "https://myapp.domain.com/oauth2/callback": domain / port not in whitelist
[2024/10/31 10:35:04] [validator.go:63] Rejecting invalid redirect "/oauth2/start?rd=https://myapp.domain.com/oauth2/callback": not an absolute or relative URL
 [2024/10/31 10:35:04] [director.go:85] Invalid redirect provided in rd querystring parameter: https://myapp.domain.com/oauth2/callback
 [2024/10/31 10:35:04] [director.go:85] Invalid redirect generated from X-Forwarded-Uri header: /oauth2/start?rd=https://myapp.domain.com/oauth2/callback
 ```

### Steps To Reproduce

- Use version 7.7.1 with ouath-proxy config:

```
    - --provider=oidc
    - --azure-tenant=<redacted.
    - --pass-access-token=true
    - --cookie-name=_proxycookie 
    - --upstream=https://myapp.domain.com.
    - --redirect-url=https://myapp.domain.com/oauth2/callback
    - --cookie-csrf-per-request=true
    - --cookie-csrf-expire=5m
    - --email-domain=*
    - --http-address=0.0.0.0:4180
    - --oidc-issuer-url=https://login.microsoftonline.com/<redacted>/v2.0
    - --user-id-claim=oid
    - --whitelist-domain=".myapp.domain.com"
    - --cookie-refresh=10m
    - --cookie-expire=1h
    - --auth-logging-format="{{.Client}} - {{.RequestID}} - {{.Username}} [{{.Timestamp}}] [{{.Status}}]"
```

oauth-proxy niginx-ingress annotations are:

```yaml
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
``` 

application ingress annotations are: 
   
```yaml
nginx.ingress.kubernetes.io/auth-url: "https://myapp.domain.com/oauth2/auth"
nginx.ingress.kubernetes.io/auth-signin: "https://myapp.domain.com/oauth2/start?rd=https://helm-releases-experimental.balticit.ifint.biz/oauth2/callback"
```

### Configuration details or additional information

When I login the following error is shown: 
![image](https://github.com/user-attachments/assets/b9cbbf87-e08f-40a9-986e-eeb05c733f42)

At the same time in the logs I see that authentication was successful,but ` [oauthproxy.go:875] Error while parsing OAuth2 state: invalid length` is thrown.

If I press go back on error page my app page successfully opens. 

Important note here that if I disable `- --whitelist-domain=".myapp.domain.com` argument everything looks good and  the app page opens as expected right after auth, but then in this case I see these errors in the log: 
```
 [2024/10/31 10:35:04] [validator.go:60] Rejecting invalid redirect "https://myapp.domain.com/oauth2/callback": domain / port not in whitelist
[2024/10/31 10:35:04] [validator.go:63] Rejecting invalid redirect "/oauth2/start?rd=https://myapp.domain.com/oauth2/callback": not an absolute or relative URL
 [2024/10/31 10:35:04] [director.go:85] Invalid redirect provided in rd querystring parameter: https://myapp.domain.com/oauth2/callback
 [2024/10/31 10:35:04] [director.go:85] Invalid redirect generated from X-Forwarded-Uri header: /oauth2/start?rd=https://myapp.domain.com/oauth2/callback
```

Same config with version 7.7.0 also drops an error in logs  but bit different one. 

```
runtime error: index out of range [0] with length 0
goroutine 81 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0xe00a80, 0xc0000de330})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/cookies.ExtractStateSubstring(0xc00025f301?)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/cookies/csrf.go:222 +0x91
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/cookies.GenerateCookieName(0x203000?, 0xc00024e520)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/cookies/csrf.go:94 +0x2c
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/cookies.LoadCSRFCookie(0xc0003aeb00, 0x0?)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/cookies/csrf.go:77 +0x27
```
Also instead of 500 page  I receive 403. 
In 7.7.0 disabling --whitelist-domain follows the success auth and redirect to the app page but has same errors like it is in 7.7.1

```
 [2024/10/31 10:35:04] [validator.go:60] Rejecting invalid redirect "https://myapp.domain.com/oauth2/callback": domain / port not in whitelist
[2024/10/31 10:35:04] [validator.go:63] Rejecting invalid redirect "/oauth2/start?rd=https://myapp.domain.com/oauth2/callback": not an absolute or relative URL
 [2024/10/31 10:35:04] [director.go:85] Invalid redirect provided in rd querystring parameter: https://myapp.domain.com/oauth2/callback
 [2024/10/31 10:35:04] [director.go:85] Invalid redirect generated from X-Forwarded-Uri header: /oauth2/start?rd=https://myapp.domain.com/oauth2/callback
 ```

**Comment by seos-vcbs** [comment]
+1

**Comment by emrobe** [comment]
+1 I have this exact same issue with 7.7.1

**Comment by angelmaturanat** [comment]
+1 I have the same problem using the 7.8.1 version

**Comment by tuunit** [comment]
@angelmaturanat @emrobe @seos-vcbs which provider are you using?

**Comment by emrobe** [comment]
@tuunit Azure. I haven't tried reconfiguring with the new Entra support, hoping this will solve the issue.

**Comment by IvayLoRD** [comment]
+1 We have the same error on AWS.

**Comment by JohnMav** [comment]
+1 getting this error as well, v7.8.1 with entra-id provider.

**Comment by tuunit** [comment]
@jjlakis let's investigate this

**Comment by tuunit** [comment]
Potentially related to

Issue #2311
PR: https://github.com/oauth2-proxy/oauth2-proxy/pull/2328

**Comment by gauravshah22** [comment]
+1

We are hitting the same issue while trying to configure oauth2-proxy as a authentication middleware with nginx. Using MS Entra as the identity provider, do we've any fix for this ? Not overriding value for CSRF cookie, will cookie-csrf-per-request be set to false by default ?

Error:
Browser shows 500 "Internal Server Error". While the oauth2-proxy log shows below message:

[oauthproxy.go:877] Error while parsing OAuth2 state: invalid length

**Comment by raphschm** [comment]
I am also having this issue - any fix?

**Comment by StarGrim33** [comment]
+ 1
Still having the problem after pulling the last version

**Comment by freick** [comment]
+1

**Comment by chehsunliu** [comment]
The error is originated from here:

https://github.com/oauth2-proxy/oauth2-proxy/blob/4c86a4d574952ffa829dbe1f5a32c48b3f2e1ddc/oauthproxy.go#L876-L881

which is from here:

https://github.com/oauth2-proxy/oauth2-proxy/blob/4c86a4d574952ffa829dbe1f5a32c48b3f2e1ddc/oauthproxy.go#L1245-L1267

It looks like it expects the `state` should be composed in the format `{nonce}:{redirect}`.

**Comment by bogi788** [comment]
In our case the problem seems to be that the state (generated by oauth2-proxy) is url-encoded twice and returned to the login callback as is - still url-encoded twice. because of this the colon is still represented as '%25' when it should be ':'.

In my case adding "--encode-state=true" to the command line helped.
